import os
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from datetime import datetime

def generate_assessment_report(assessment):
    """
    Generates a PDF bytes object for a given AssessmentSession.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='CenterTitle', alignment=TA_CENTER, fontSize=18, spaceAfter=20, fontName="Helvetica-Bold"))
    
    elements = []
    
    # Header
    elements.append(Paragraph("NeuroSense AI Enterprise Edition", styles['CenterTitle']))
    elements.append(Paragraph("Clinical Pathology Report", styles['Title']))
    elements.append(Spacer(1, 20))
    
    # Patient Info
    patient = assessment.patient
    # Some older generated patients might not have these methods natively exposed but let's safely get them
    first_name = patient.user.first_name if patient.user and patient.user.first_name else 'Unknown'
    last_name = patient.user.last_name if patient.user and patient.user.last_name else 'Patient'
    
    p_info = [
        ["Patient Name", f"{first_name} {last_name}"],
        ["Patient UUID", patient.id],
        ["Date of Birth", patient.date_of_birth.strftime('%Y-%m-%d') if patient.date_of_birth else 'N/A'],
        ["Gender", patient.gender],
        ["Assessment ID", assessment.id],
        ["Session Date", assessment.session_date.strftime('%Y-%m-%d %H:%M')],
    ]
    t = Table(p_info, colWidths=[150, 300])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    elements.append(t)
    elements.append(Spacer(1, 30))
    
    # Test Results
    elements.append(Paragraph("Multimodal AI Pipeline Results", styles['Heading2']))
    
    def safe_fmt(val):
        return f"{val:.1f}%" if val is not None else "N/A"
        
    results = [
        ["Modality", "Risk Score", "Status"],
        ["Voice Phonation", safe_fmt(assessment.voice_risk_score), "Completed" if assessment.voice_risk_score else "Pending"],
        ["Handwriting (Micrographia)", safe_fmt(assessment.handwriting_risk_score), "Completed" if assessment.handwriting_risk_score else "Pending"],
        ["Gait / Video AI", safe_fmt(assessment.gait_risk_score), "Completed" if assessment.gait_risk_score else "Pending"],
        ["Fusion Meta-Classifier", safe_fmt(assessment.composite_risk_score), "Finalized" if assessment.composite_risk_score else "Pending"],
    ]
    
    t2 = Table(results, colWidths=[200, 125, 125])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#4f46e5")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.ghostwhite),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    elements.append(t2)
    elements.append(Spacer(1, 30))
    
    # Interpretation Note
    composite = assessment.composite_risk_score if assessment.composite_risk_score else 0
    if composite > 70:
        interp = "HIGH RISK INDICATOR. The AI Multi-modal baseline heavily correlates with Parkinsonian phenotypes."
    elif composite > 40:
        interp = "MODERATE RISK INDICATOR. Further clinical monitoring is advised."
    else:
        interp = "LOW RISK INDICATOR. Patient signals are within normal neuro-motor ranges."
        
    elements.append(Paragraph("AI Fusion Interpretation", styles['Heading3']))
    elements.append(Paragraph(interp, styles['Normal']))
    elements.append(Spacer(1, 20))
    
    # Custom Doctor Notes
    if assessment.doctor_notes:
        elements.append(Paragraph("Physician Notes", styles['Heading3']))
        elements.append(Paragraph(assessment.doctor_notes, styles['Normal']))
        
    elements.append(Spacer(1, 40))
    elements.append(Paragraph(f"Securely cryptographically generated by NeuroSense Enterprise Engine on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Italic']))
    
    doc.build(elements)
    pdf = buffer.getvalue()
    buffer.close()
    return pdf
